"""initial production schema

Revision ID: 4489344615a9
Revises: 
Create Date: 2026-07-19 00:25:33.834280
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4489344615a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('location', sa.String(length=240), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('property_type', sa.String(length=40), nullable=False),
    sa.Column('asking_price_usd', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Float(), nullable=False),
    sa.Column('area_sq_m', sa.Float(), nullable=False),
    sa.Column('listing_status', sa.String(length=20), nullable=False),
    sa.Column('readiness', sa.String(length=20), nullable=False),
    sa.Column('handover_label', sa.String(length=80), nullable=True),
    sa.Column('tour_type', sa.String(length=20), nullable=False),
    sa.Column('tour_url', sa.Text(), nullable=True),
    sa.Column('images', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('parking', sa.Integer(), nullable=True),
    sa.Column('features', sa.Text(), nullable=False),
    sa.Column('floor_plan_url', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('source_label', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('area_sq_m > 0', name='ck_listings_area_positive'),
    sa.CheckConstraint('asking_price_usd > 0', name='ck_listings_price_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_listings_public_catalog', 'listings', ['published', 'listing_status', 'district'], unique=False)
    op.create_table('rate_limit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_hash', sa.String(length=64), nullable=False),
    sa.Column('route', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rate_limit_window', 'rate_limit_events', ['client_hash', 'route', 'created_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=True),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('budget_usd', sa.Float(), nullable=True),
    sa.Column('preferred_channel', sa.String(length=24), nullable=False),
    sa.Column('consent_to_contact', sa.Boolean(), nullable=False),
    sa.Column('consent_privacy', sa.Boolean(), nullable=False),
    sa.Column('consent_marketing', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('delivery_status', sa.String(length=24), nullable=False),
    sa.Column('delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.String(length=300), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('rights_basis', sa.String(length=240), nullable=False),
    sa.Column('rights_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_media_listing_order', 'media', ['listing_id', 'sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_listing_order', table_name='media')
    op.drop_table('media')
    op.drop_table('inquiries')
    op.drop_table('audit_events')
    op.drop_index('ix_rate_limit_window', table_name='rate_limit_events')
    op.drop_table('rate_limit_events')
    op.drop_index('ix_listings_public_catalog', table_name='listings')
    op.drop_table('listings')
    op.drop_table('areas')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
